type Ersatz = string | ((...teile: string[]) => string);

const WOERTER: Record<string, string> = {
  "Kamera": "Camera",
  "Wecker & Timer": "Alarms & timers",
  "Bilder": "Images",
  "Bibliothek": "Library",
  "Projekte": "Projects",
  "Fernzugriff": "Remote access",
  "Planen": "Schedule",
  "Bildschirmzeit": "Screen time",
  "Handy-KI": "Phone AI",
  "Eigener Zugang": "Own access",
  "Kein Pi": "No Pi",
  "Pi nicht erreichbar. Heimnetz oder Tailscale prüfen.": "Pi not reachable. Check your home network or Tailscale.",
  "📷 Foto": "📷 Photo",
  "🎤 Sprachnachricht": "🎤 Voice message",
  "📎 Datei": "📎 File",
  "Suchen": "Search",
  "Angeheftet": "Pinned",
  "Letzte": "Recent",
  "Handy": "Phone",
  "Deine Chats erscheinen hier.": "Your chats will appear here.",
  "Verbinde dein Gerät mit deinem Pi oder nutze Jon ohne PC.": "Connect your device to your Pi or use Jon without a PC.",
  "Archivierte Chats": "Archived chats",
  "Einstellungen": "Settings",
  "Mit Jon sprechen": "Talk to Jon",
  "Schließen": "Close",
  "Bereit für eine Pause?": "Ready for a break?",
  "Du bist schon eine Weile hier. Kurz aufstehen, etwas trinken – Jon wartet solange auf dich.": "You've been here a while. Stand up, have a drink – Jon will wait for you.",
  "Darüber lassen sich neue Apps installieren": "New apps can be installed through it",
  "Apps für Jon": "Apps for Jon",
  "1 App freigeben": "Allow 1 app",
  "Diese Apps lassen sich aus Jon öffnen. Im Kiosk sind nur sie erreichbar, und für sie gelten Limits und Schlafenszeit.": "These apps can be opened from Jon. In kiosk mode only they are reachable, and limits and bedtime apply to them.",
  "App suchen": "Search apps",
  "Freigegeben": "Allowed",
  "Weitere Apps": "More apps",
  "Keine App gefunden.": "No app found.",
  "Alle Befehle anzeigen": "Show all commands",
  "Neuen Chat starten": "Start a new chat",
  "Zu Work wechseln": "Switch to Work",
  "Zu Chat wechseln": "Switch to Chat",
  "<Idee>": "<idea>",
  "Website bauen und ansehen": "Build and view a website",
  "<Thema>": "<topic>",
  "Podcast mit zwei Stimmen": "Podcast with two voices",
  "<Beschreibung>": "<description>",
  "Bild erstellen": "Create image",
  "<Frage>": "<question>",
  "Im Web suchen": "Search the web",
  "[Ort]": "[place]",
  "Wetter anzeigen": "Show weather",
  "Datei hochladen und auswerten": "Upload and analyze a file",
  "Foto machen und Jon fragen": "Take a photo and ask Jon",
  "<Uhrzeit>": "<time>",
  "Wecker stellen": "Set an alarm",
  "<Minuten>": "<minutes>",
  "Timer starten": "Start a timer",
  "[Minuten]": "[minutes]",
  "Fokuszeit starten": "Start focus time",
  "Schritte von heute": "Today's steps",
  "<Training>": "<workout>",
  "Training eintragen": "Log a workout",
  "Bildschirmzeit öffnen": "Open screen time",
  "[Sekunden]": "[seconds]",
  "Video vom Bildschirm deines PCs": "Video of your PC screen",
  "[1|2|alle]": "[1|2|all]",
  "Bildschirm live ansehen": "Watch the screen live",
  "Live-Ansicht beenden": "End live view",
  "Alle verbundenen Jon-Geräte": "All connected Jon devices",
  "Tiefenrecherche starten": "Start deep research",
  "Stand der Recherche": "Research status",
  "Recherche abbrechen": "Cancel research",
  "Recherche fortsetzen": "Resume research",
  "[Name]": "[name]",
  "Modell anzeigen oder wechseln": "Show or change the model",
  "KI-Anbieter wechseln": "Switch AI provider",
  "Jon liest Antworten vor": "Jon reads answers aloud",
  "Nur noch Text": "Text only",
  "Offline-KI verwalten": "Manage offline AI",
  "Notruf an deine Familie": "Emergency call to your family",
  "Laufende Antwort abbrechen": "Stop the current answer",
  "Gespräch neu beginnen": "Restart the conversation",
  "Erledigt.": "Done.",
  "Kein Bild.": "No image.",
  "Alle": "All",
  "Bildschirm": "Screen",
  "Diese Funktion braucht die Jon-App auf dem Gerät.": "This feature needs the Jon app on the device.",
  "Der Pi antwortet nicht. Verbindung prüfen.": "The Pi isn't responding. Check the connection.",
  "Dateiübertragung unterbrochen.": "File transfer interrupted.",
  "Datei": "File",
  "Auf deinem Pi": "On your Pi",
  "· wird geladen …": "· loading …",
  "· Tippen zum Öffnen": "· tap to open",
  "Herunterladen": "Download",
  "Download beginnt": "Download starting",
  "Uhren auf deinem Pi": "Clocks on your Pi",
  "Wecker": "Alarm",
  "Stoppuhr": "Stopwatch",
  "Fertig": "Done",
  "Läuft": "Running",
  "Pausiert": "Paused",
  "Startet": "Starting",
  "Video abspielen": "Play video",
  "Bildschirmvideo": "Screen video",
  "Auf dem PC": "On the PC",
  "Aufs Handy": "To the phone",
  "Bild speichern": "Save image",
  "Bild in Downloads/Jon gespeichert.": "Image saved to Downloads/Jon.",
  "Browser-Aufgabe": "Browser task",
  "Link kopiert.": "Link copied.",
  "Was für eine Website?": "What kind of website?",
  "Baut sie und zeigt sie dir": "Builds it and shows it to you",
  "Worum geht's im Podcast?": "What's the podcast about?",
  "Zwei Stimmen, als Audiodatei": "Two voices, as an audio file",
  "Was soll Jon recherchieren?": "What should Jon research?",
  "Jon recherchiert gründlich im Web": "Jon researches the web thoroughly",
  "Thema der Präsentation": "Presentation topic",
  "Präsentation": "Presentation",
  "PowerPoint mit Folien": "PowerPoint with slides",
  "Was soll ins Dokument?": "What should go into the document?",
  "Dokument": "Document",
  "Word, PDF, Excel, Text": "Word, PDF, Excel, text",
  "Was soll Jon im Web erledigen?": "What should Jon do on the web?",
  "Browser-Agent": "Browser agent",
  "Jon erledigt Webaufgaben": "Jon handles web tasks",
  "Welcher Befehl auf dem Pi?": "Which command on the Pi?",
  "Befehle auf dem Pi": "Commands on the Pi",
  "Wohin oder was suchst du?": "Where to, or what are you looking for?",
  "Orte, Routen und Umgebung": "Places, routes and surroundings",
  "Wonach soll Jon suchen?": "What should Jon search for?",
  "Websuche": "Web search",
  "Aktuelle Infos aus dem Netz": "Current info from the web",
  "Beschreibe dein Bild": "Describe your image",
  "Jon malt ein Bild": "Jon paints a picture",
  "Für welchen Ort?": "For which place?",
  "Wetter": "Weather",
  "Vorhersage für deinen Ort": "Forecast for your location",
  "Was hast du trainiert?": "What did you train?",
  "Wie lange?": "How long?",
  "Timer und Wecker am Handy": "Timers and alarms on the phone",
  "Welcher Termin?": "Which appointment?",
  "Kalender": "Calendar",
  "Termine eintragen": "Add appointments",
  "Was möchtest du hören?": "What would you like to hear?",
  "Musik": "Music",
  "Amazon Music abspielen": "Play Amazon Music",
  "Bitte eine Datei bis 4 MB auswählen.": "Please choose a file up to 4 MB.",
  "Datei konnte nicht gelesen werden.": "The file couldn't be read.",
  "Auf dem Handy": "On the phone",
  "Nachgedacht": "Thought it over",
  "Datei:": "File:",
  "Danke für dein Feedback.": "Thanks for your feedback.",
  "Kopieren": "Copy",
  "Kopiert.": "Copied.",
  "Gute Antwort": "Good answer",
  "Schlechte Antwort": "Bad answer",
  "Vorlesen": "Read aloud",
  "Teilen": "Share",
  "Mehr": "More",
  "Antwort": "Answer",
  "In Downloads/Jon gespeichert.": "Saved to Downloads/Jon.",
  "Als Datei speichern": "Save as file",
  "An WhatsApp senden": "Send to WhatsApp",
  "Mit Jons Stimme vorlesen": "Read aloud with Jon's voice",
  "Ziel beschreiben": "Describe the goal",
  "Aufgabe für Work": "Task for Work",
  "Antworten": "Reply",
  "Jon fragen": "Ask Jon",
  "Jon antworten": "Reply to Jon",
  "Diktat abbrechen": "Cancel dictation",
  "Diktat übernehmen": "Use dictation",
  "Hinzufügen": "Add",
  "Nachricht an Jon": "Message to Jon",
  "Werkzeug entfernen": "Remove tool",
  "Diktieren": "Dictate",
  "Antwort stoppen": "Stop answer",
  "Senden": "Send",
  "Stimme": "Voice",
  "Jon schaut sich das Bild an …": "Jon is looking at the image …",
  "Datei wählen …": "Choose file …",
  "Fertig transkribiert.": "Transcription finished.",
  "Datei ist bereit.": "File is ready.",
  "Jon konnte keinen Plan erstellen.": "Jon couldn't create a plan.",
  "Schreib zuerst eine Nachricht, dann kann Jon den Chat speichern.": "Write a message first, then Jon can save the chat.",
  "Du": "You",
  "Eine Website bauen und ansehen": "Build and view a website",
  "Einen Podcast aufnehmen lassen": "Have a podcast recorded",
  "Auf deinem Pi arbeiten": "Work on your Pi",
  "Hilfe bei den Hausaufgaben": "Help with homework",
  "Aufgabe fotografieren": "Photograph the task",
  "Automatisch": "Automatic",
  "Loslösen": "Unpin",
  "Anpinnen": "Pin",
  "Losgelöst.": "Unpinned.",
  "Angeheftet.": "Pinned.",
  "Umbenennen": "Rename",
  "Zum Projekt hinzufügen": "Add to project",
  "Hochgeladene Dateien": "Uploaded files",
  "Im Chat suchen": "Search in chat",
  "Vom Startbildschirm entfernen": "Remove from home screen",
  "Zum Startbildschirm hinzufügen": "Add to home screen",
  "Vom Startbildschirm entfernt.": "Removed from home screen.",
  "Auf dem Startbildschirm.": "On the home screen.",
  "Aus Archiv holen": "Unarchive",
  "Archivieren": "Archive",
  "Chat archiviert.": "Chat archived.",
  "Löschen": "Delete",
  "Menü öffnen": "Open menu",
  "Temporärer Chat": "Temporary chat",
  "Temporärer Chat aus.": "Temporary chat off.",
  "Temporärer Chat: wird nirgends gespeichert.": "Temporary chat: not saved anywhere.",
  "Neuer Chat": "New chat",
  "Chatmenü": "Chat menu",
  "Temporär ·": "Temporary ·",
  "Mit deinem Pi verbinden": "Connect to your Pi",
  "Pi offline · Verbindung wird gesucht": "Pi offline · looking for a connection",
  "Woran arbeiten wir?": "What are we working on?",
  "Hallo!": "Hello!",
  "Beschreib dein Ziel – Jon plant, arbeitet Schritt für Schritt und zeigt dir das Ergebnis.": "Describe your goal – Jon plans, works step by step and shows you the result.",
  "Websites, Dokumente, Code und mehr.": "Websites, documents, code and more.",
  "Was kann ich heute für dich tun?": "What can I do for you today?",
  "Wartet auf deine Freigabe": "Waiting for your approval",
  "Jon arbeitet …": "Jon is working …",
  "Nachricht erneut bearbeiten": "Edit message again",
  "Jon möchte eine Aktion ausführen": "Jon wants to perform an action",
  "Ablehnen": "Decline",
  "Erlauben": "Allow",
  "Nicht mehr fragen …": "Don't ask again …",
  "Transkript bereit": "Transcript ready",
  "Video ausgewertet": "Video analyzed",
  "Bild": "Image",
  "Auf dem Pi": "On the Pi",
  "Einrichtungsmodus · Kiosk noch aus": "Setup mode · kiosk still off",
  "Datei vom Handy": "File from the phone",
  "Bilder, Videos, Audio, PDFs – Jon wertet sie aus": "Images, videos, audio, PDFs – Jon analyzes them",
  "Foto aufnehmen": "Take a photo",
  "Jon schaut es sich an": "Jon takes a look",
  "Aus der Bibliothek": "From the library",
  "Werkzeuge": "Tools",
  "im Eingabefeld zeigt dir alle": "in the input field shows you all",
  "Befehle": "Commands",
  "Anbieter und Modell": "Provider and model",
  "Wohin mit der Datei?": "Where should the file go?",
  "Jon wertet die Datei auf jeden Fall aus: Bilder werden beschrieben, Videos angesehen und Sprache wird zu Text.": "Jon analyzes the file either way: images get described, videos watched and speech turned into text.",
  "Auf den Pi hochladen": "Upload to the Pi",
  "· landet in deiner Bibliothek": "· ends up in your library",
  "Nur auf dem Handy": "Only on the phone",
  "Bleibt in Jons Ordner auf diesem Gerät": "Stays in Jon's folder on this device",
  "Text kopieren": "Copy text",
  "Chat umbenennen": "Rename chat",
  "Speichern": "Save",
  "Noch keine Projekte.": "No projects yet.",
  "Neues Projekt": "New project",
  "Dateien in diesem Chat": "Files in this chat",
  "In diesem Chat gibt es noch keine Dateien auf dem Pi.": "This chat has no files on the Pi yet.",
  "Hochgeladen": "Uploaded",
  "Chat löschen?": "Delete chat?",
  "Chat gelöscht.": "Chat deleted.",
  "Endgültig löschen": "Delete permanently",
  "Das Wichtigste": "The essentials",
  "Kein Konto bei FelWorks, keine Werbung, kein Tracking, keine Analyse-Dienste. FelWorks betreibt keinen Server, über den deine Daten laufen.": "No FelWorks account, no ads, no tracking, no analytics. FelWorks runs no server your data passes through.",
  "Auf diesem Handy": "On this phone",
  "Offline-Chats, Erinnerungen, Fitness, Wecker, Bildschirmzeit-Regeln, Jons Arbeitsordner und Offline-Modelle bleiben im geschützten App-Speicher. API-Schlüssel und Zugangsdaten sind mit dem Android-Schlüsselspeicher verschlüsselt.": "Offline chats, memories, fitness, alarms, screen time rules, Jon's work folder and offline models stay in protected app storage. API keys and credentials are encrypted with the Android keystore.",
  "Zu deinem Jon am PC oder Pi": "To your Jon on the PC or Pi",
  "Chats, Dateien, Sicherungen und für die Eltern-Übersicht der Gerätestatus gehen nur an deinen eigenen Jon – Ende-zu-Ende verschlüsselt über WLAN oder Tailscale.": "Chats, files, backups and – for the parent overview – the device status only go to your own Jon, end-to-end encrypted via Wi-Fi or Tailscale.",
  "KI-Anbieter und Dienste": "AI providers and services",
  "Nur wenn du sie nutzt: deine Nachrichten an den gewählten KI-Anbieter, Suchanfragen an DuckDuckGo und Wikipedia, Orte an Open-Meteo, Modell-Downloads über Hugging Face und das Sprachmodell für Live-Text von alphacephei.com. Offline-Modelle senden nichts.": "Only when you use them: your messages to the chosen AI provider, searches to DuckDuckGo and Wikipedia, places to Open-Meteo, model downloads via Hugging Face and the live-text speech model from alphacephei.com. Offline models send nothing.",
  "Familie": "Family",
  "Kindersicherung, SOS und Anfragen nach mehr Zeit gehen nur an den Jon deiner Familie und, falls eingerichtet, an euren Telegram-Bot.": "Parental controls, SOS and requests for more time only go to your family's Jon and, if set up, to your Telegram bot.",
  "Mikrofon": "Microphone",
  "Sprechen und Diktieren – nur wenn du auf den Knopf tippst": "Talking and dictation – only when you tap the button",
  "Fotos für Jon und QR-Codes zum Koppeln": "Photos for Jon and QR codes for pairing",
  "Benachrichtigungen": "Notifications",
  "Wecker, Timer, Jon Chat und Durchsagen": "Alarms, timers, Jon Chat and announcements",
  "Körperliche Aktivität": "Physical activity",
  "Schrittzähler": "Step counter",
  "Nutzungszugriff": "Usage access",
  "Bildschirmzeit der freigegebenen Apps": "Screen time of the allowed apps",
  "Standort": "Location",
  "Nur beim SOS, wenn du es einschaltest": "Only for SOS, if you turn it on",
  "Telefon": "Phone",
  "Nur für den Anruf nach einem SOS": "Only for the call after an SOS",
  "Gerätemodus": "Device mode",
  "Nur für den Kiosk der Kindersicherung": "Only for the parental control kiosk",
  "Datenschutz": "Privacy",
  "Berechtigungen": "Permissions",
  "Link zur Datenschutzerklärung kopiert.": "Link to the privacy policy copied.",
  "Alle Daten löschen": "Delete all data",
  "Setzt Jon auf diesem Handy komplett zurück": "Completely resets Jon on this phone",
  "Alle Daten löschen?": "Delete all data?",
  "Jon vergisst auf diesem Handy alles: Chats, Erinnerungen, Fitness, Wecker, Regeln, Schlüssel und Offline-Modelle. Die Kopplung mit deinem PC oder Pi wird aufgehoben, der Kiosk beendet. Danach startet Jon neu wie am ersten Tag.": "Jon forgets everything on this phone: chats, memories, fitness, alarms, rules, keys and offline models. The pairing with your PC or Pi is removed and the kiosk ends. Then Jon restarts as on day one.",
  "Auch Fotos und Downloads von Jon": "Also Jon's photos and downloads",
  "Galerie „Jon“ und Download/Jon": "Gallery “Jon” and Download/Jon",
  "Wird gelöscht …": "Deleting …",
  "Mo": "Mon",
  "Di": "Tue",
  "Mi": "Wed",
  "Do": "Thu",
  "Fr": "Fri",
  "Sa": "Sat",
  "So": "Sun",
  "Zeit aufgebraucht": "Time used up",
  "Schlafenszeit": "Bedtime",
  "Pause": "Break",
  "Min.": "min",
  "Warum? (freiwillig)": "Why? (optional)",
  "Zum Beispiel: Hausaufgaben sind fertig": "For example: homework is done",
  "Mehr Zeit": "More time",
  "Gesperrt": "Locked",
  "Deine Eltern bekommen die Anfrage sofort und können mit einem Tipp Ja sagen.": "Your parents get the request right away and can say yes with one tap.",
  "Anfrage gesendet. Ich sag dir Bescheid, sobald die Antwort da ist.": "Request sent. I'll let you know as soon as the answer arrives.",
  "Anfrage läuft": "Request pending",
  "die App": "the app",
  "Mehr Zeit anfragen": "Ask for more time",
  "Abbrechen": "Cancel",
  "Jon wird gesucht": "Someone is looking for Jon",
  "Hier bin ich!": "Here I am!",
  "Tippe auf Gefunden, dann höre ich auf zu klingeln.": "Tap Found and I'll stop ringing.",
  "Schlummern · 5 Min.": "Snooze · 5 min",
  "Gefunden": "Found",
  "Stopp": "Stop",
  "Durchsage": "Announcement",
  "Verstanden": "Got it",
  "Gute Nacht": "Good night",
  "Ja, klar!": "Yes, sure!",
  "Diesmal nicht": "Not this time",
  "öffnen": "open",
  "Jon ruft jetzt an.": "Jon is calling now.",
  "Jon ruft gleich an.": "Jon is about to call.",
  "Deine Familie wurde benachrichtigt.": "Your family has been notified.",
  "SOS – lange drücken": "SOS – long press",
  "Kindgerechte Antworten": "Child-friendly answers",
  "Einfache Sprache, passend zum Alter.": "Simple language, matched to age.",
  "Hausaufgaben-Hilfe": "Homework help",
  "Jon erklärt Schritt für Schritt, statt nur die Lösung zu verraten.": "Jon explains step by step instead of just giving away the answer.",
  "Sichere Suche": "Safe search",
  "SafeSearch ist an, Seiten für Erwachsene werden aussortiert.": "SafeSearch is on, adult sites are filtered out.",
  "Keine riskanten Aktionen": "No risky actions",
  "Keine Befehle am PC, keine Dateien, keine Webcam.": "No commands on the PC, no files, no webcam.",
  "Hilfe bei Sorgen": "Help with worries",
  "Bei Kummer verweist Jon auf Eltern und Rat auf Draht (147).": "When something's wrong, Jon points to parents and helplines like Rat auf Draht (147).",
  "Kinder-Modus": "Kids mode",
  "Aus": "Off",
  "Kinder-Modus ist an.": "Kids mode is on.",
  "Kinder-Modus ist aus.": "Kids mode is off.",
  "Alter": "Age",
  "Gilt für Jon auf dem PC oder Pi, für deinen eigenen Zugang und für die Offline-KI auf dem Handy.": "Applies to Jon on the PC or Pi, to your own access and to the offline AI on the phone.",
  "Ohne Standortfreigabe kann Jon den Ort nicht mitschicken.": "Without location permission Jon can't send the location.",
  "Trag zuerst eine Telefonnummer ein.": "Enter a phone number first.",
  "Lange auf SOS drücken schickt sofort eine Nachricht an deine Familie – an Jon am PC oder Pi und per Telegram.": "Long-pressing SOS immediately sends a message to your family – to Jon on the PC or Pi and via Telegram.",
  "Standort mitschicken": "Send location",
  "Standortfreigabe fehlt noch": "Location permission still missing",
  "Deine Eltern sehen, wo du bist": "Your parents see where you are",
  "Danach direkt anrufen": "Then call right away",
  "Dieses Gerät kann nicht telefonieren": "This device can't make calls",
  "Nach dem SOS eine Nummer wählen": "Dial a number after the SOS",
  "Wer?": "Who?",
  "Zum Beispiel: Papa": "For example: Dad",
  "Telefonnummer": "Phone number",
  "SOS-Einstellungen gespeichert.": "SOS settings saved.",
  "Ohne Anruf-Erlaubnis öffnet Jon die Nummer im Telefon – dann nur noch auf Anrufen tippen.": "Without call permission Jon opens the number in the phone app – then just tap call.",
  "am Tag": "a day",
  "Schritte diese Woche": "steps this week",
  "Alles frei": "All free",
  "ohne Limit": "no limit",
  "Min. genutzt": "min used",
  "Anfrage läuft – warte auf Antwort": "Request pending – waiting for an answer",
  "Diese Woche": "This week",
  "Fokuszeit": "Focus time",
  "Sperrt alle freigegebenen Apps für eine Weile – ideal zum Lernen. Beenden kann sie nur ein Erwachsener.": "Locks all allowed apps for a while – ideal for studying. Only an adult can end it.",
  "Für Eltern": "For parents",
  "Tageslimits": "Daily limits",
  "Keine Limits": "No limits",
  "Pause beenden": "End break",
  "Pause beendet.": "Break ended.",
  "Jetzt Pause": "Break now",
  "Apps sofort sperren": "Lock apps right away",
  "Genauer messen": "Measure more precisely",
  "Mit „Nutzungszugriff“ zählt Jon auch, wenn Apps nicht über Jon geöffnet werden.": "With “usage access” Jon also counts when apps aren't opened through Jon.",
  "Nutzungszugriff erlauben": "Allow usage access",
  "Ohne Gerätemodus kann Jon Apps nur beim Öffnen über Jon sperren. Mit Gerätemodus sperrt er sie überall.": "Without device mode Jon can only lock apps opened through Jon. With device mode it locks them everywhere.",
  "Limits gespeichert.": "Limits saved.",
  "Von": "From",
  "Bis": "Until",
  "An diesen Abenden": "On these evenings",
  "Gesperrte Apps": "Locked apps",
  "Schlafenszeit gespeichert.": "Bedtime saved.",
  "Schlafenszeit aus.": "Bedtime off.",
  "Wie lange sollen alle freigegebenen Apps gesperrt sein?": "How long should all allowed apps be locked?",
  "Laufen": "Running",
  "Rad": "Cycling",
  "Schwimmen": "Swimming",
  "Wandern": "Hiking",
  "Schritte zählen": "Count steps",
  "Erlaube „Körperliche Aktivität“, dann zählt Jon deine Schritte.": "Allow “physical activity” and Jon will count your steps.",
  "Trainings diese Woche": "Workouts this week",
  "Tage in Folge": "Days in a row",
  "Minuten": "Minutes",
  "Ziele": "Goals",
  "Plan von Jon": "Plan from Jon",
  "Letzte Trainings": "Recent workouts",
  "Noch nichts eingetragen. Tippe auf Plus oder sag Jon einfach: „Ich war im Gym, Bankdrücken 3x10 mit 60 kg.“": "Nothing logged yet. Tap plus or just tell Jon: “I was at the gym, bench press 3x10 with 60 kg.”",
  "Rekorde": "Records",
  "Titel (optional)": "Title (optional)",
  "Morgenrunde": "Morning run",
  "Übungen": "Exercises",
  "Bankdrücken 3x10 60kg, Kniebeugen 4x8 80kg, 20 Liegestütze": "Bench press 3x10 60kg, squats 4x8 80kg, 20 push-ups",
  "Heute": "Today",
  "Gestern": "Yesterday",
  "Eintragen": "Log",
  "Deine Ziele": "Your goals",
  "Schritte pro Tag": "Steps per day",
  "Trainings pro Woche": "Workouts per week",
  "Training löschen?": "Delete workout?",
  "“ wird aus deinem Tagebuch entfernt.": "” will be removed from your journal.",
  "Gelöscht.": "Deleted.",
  "Sprachnachricht": "Voice message",
  "Text anzeigen": "Show text",
  "Jon Chat braucht deinen Pi": "Jon Chat needs your Pi",
  "Freunde-Chat läuft über Jon am PC oder Pi. Verbinde dein Gerät, dann schreibst du hier wie gewohnt.": "Friends chat runs through Jon on the PC or Pi. Connect your device and chat here as usual.",
  "schreibt …": "is typing …",
  "wartet auf Annahme": "waiting for acceptance",
  "Zurück": "Back",
  "Schreib die erste Nachricht. Alles ist Ende-zu-Ende verschlüsselt.": "Write the first message. Everything is end-to-end encrypted.",
  "Nachricht gelöscht": "Message deleted",
  "Medien": "Media",
  "Foto": "Photo",
  "Nachricht": "Message",
  "Gespeichert.": "Saved.",
  "Für mich löschen": "Delete for me",
  "Für alle löschen": "Delete for everyone",
  "Freund hinzufügen": "Add friend",
  "Wie heißt du im Jon Chat?": "What's your name in Jon Chat?",
  "Dein Name": "Your name",
  "Dein Jon-Code:": "Your Jon code:",
  "Code kopieren": "Copy code",
  "Jon-Code kopiert.": "Jon code copied.",
  "In allen Chats suchen": "Search all chats",
  "Anfragen": "Requests",
  "möchte mit dir schreiben": "wants to chat with you",
  "Annehmen": "Accept",
  "Blockieren": "Block",
  "Einladung von": "Invitation from",
  "Beitreten": "Join",
  "Gruppe": "Group",
  "Noch keine Freunde. Tippe oben auf das Plus und gib den Namen (im selben WLAN) oder den Jon-Code deines Freundes ein.": "No friends yet. Tap the plus at the top and enter your friend's name (on the same Wi-Fi) or Jon code.",
  "Im selben WLAN reicht der Name. Woanders braucht Jon den Jon-Code deines Freundes.": "On the same Wi-Fi the name is enough. Elsewhere Jon needs your friend's Jon code.",
  "Name oder Jon-Code": "Name or Jon code",
  "Anfrage gesendet.": "Request sent.",
  "Anfrage senden": "Send request",
  "Neue Gruppe": "New group",
  "Name der Gruppe": "Group name",
  "Gruppe erstellt. Die Eingeladenen müssen beitreten.": "Group created. The invited people need to join.",
  "Gruppe erstellen": "Create group",
  "1 Foto gespeichert.": "1 photo saved.",
  "Foto machen": "Take photo",
  "Fotos landen in deiner Galerie unter „Jon“.": "Photos go to your gallery under “Jon”.",
  "Noch keine Fotos": "No photos yet",
  "Mach dein erstes Foto – Jon kann es dir auch erklären.": "Take your first photo – Jon can explain it to you, too.",
  "Foto gelöscht.": "Photo deleted.",
  "Ziel": "Destination",
  "In der Nähe": "Nearby",
  "Karte konnte nicht geladen werden.": "The map couldn't be loaded.",
  "Kartenstil vom Pi nicht erreichbar.": "Map style from the Pi not reachable.",
  "Karte schließen": "Close map",
  "Satellit": "Satellite",
  "Alles zeigen": "Show all",
  "Nicht geladen": "Not loaded",
  "Wird gestartet …": "Starting …",
  "Bereit": "Ready",
  "Denkt nach …": "Thinking …",
  "Fehler": "Error",
  "Offline-KI": "Offline AI",
  "Liste aktualisieren": "Refresh list",
  "Modellliste aktualisiert.": "Model list refreshed.",
  "Jon ohne Internet": "Jon without internet",
  "Die Modelle aus Googles AI Edge Gallery laufen direkt auf deinem Handy. Keine Daten verlassen das Gerät.": "The models from Google's AI Edge Gallery run directly on your phone. No data leaves the device.",
  "Offline-Chat starten": "Start offline chat",
  "Sprache": "Language",
  "Passt aufs Handy": "Fits on the phone",
  "Knapp": "Tight",
  "Schlüssel nötig": "Key needed",
  "· wartet auf WLAN": "· waiting for Wi-Fi",
  "Nochmal": "Again",
  "Laden": "Load",
  "Abgebrochen.": "Canceled.",
  "Abgebrochen": "Canceled",
  "Als Standard": "Make default",
  "Alle passenden laden": "Load all that fit",
  "Lädt jedes Modell, das auf dieses Handy passt": "Loads every model that fits this phone",
  "Downloads gestartet.": "Downloads started.",
  "Auch über mobile Daten": "Also over mobile data",
  "Sonst nur im WLAN": "Otherwise only on Wi-Fi",
  "Hugging-Face-Schlüssel": "Hugging Face key",
  "Hinterlegt": "Stored",
  "Für Gemma 3n und Gemma 3 1B": "For Gemma 3n and Gemma 3 1B",
  "Gemma 4 E2B kann am meisten: Text, Bilder und Sprache – braucht aber 2,6 GB. Wenig Platz? Gemma 3 1B braucht nur 0,6 GB. Große Modelle laden am besten über Nacht am Ladekabel.": "Gemma 4 E2B can do the most: text, images and speech – but it needs 2.6 GB. Short on space? Gemma 3 1B needs only 0.6 GB. Large models are best loaded overnight while charging.",
  "Speicher sparen": "Save storage",
  "Android hält den Kiosk noch fest": "Android is still holding the kiosk",
  "Eine Systemseite ist hängen geblieben. Ein Neustart gibt alle Apps wieder frei.": "A system page got stuck. A restart frees all apps again.",
  "Jetzt neu starten": "Restart now",
  "An · Jon behält nur ein Offline-Modell": "On · Jon keeps only one offline model",
  "Aus · mehrere Modelle erlaubt": "Off · several models allowed",
  "Jon behält jetzt nur das Standardmodell.": "Jon now keeps only the default model.",
  "Mehrere Modelle erlaubt.": "Several models allowed.",
  "Nur Standard behalten": "Keep only the default",
  "Andere Modelle gelöscht.": "Other models deleted.",
  "Sparsam": "Compact",
  "Android hält den Kiosk noch fest. Starte das Handy einmal neu.": "Android is still holding the kiosk. Please restart the phone once.",
  "Für die Offline-Abschrift lädt Jon gerade das Sprachmodell (45 MB). Versuch es gleich nochmal.": "Jon is downloading the speech model (45 MB) for offline transcription. Try again in a moment.",
  "Manche Modelle von Google gibt es nur nach Zustimmung zur Lizenz. Melde dich auf huggingface.co an, akzeptiere die Gemma-Lizenz und erstelle unter Settings → Access Tokens einen Schlüssel (Lesen reicht).": "Some Google models are only available after accepting the license. Sign in at huggingface.co, accept the Gemma license and create a key under Settings → Access Tokens (read access is enough).",
  "Schlüssel": "Key",
  "Schlüssel gespeichert.": "Key saved.",
  "Schlüssel entfernt.": "Key removed.",
  "Auf Jon verzichten": "Go without Jon",
  "Jon läuft auf diesem Handy": "Jon runs on this phone",
  "Jon läuft über deinen PC oder Pi": "Jon runs through your PC or Pi",
  "Mit deinem eigenen Zugang – ganz ohne PC.": "With your own access – no PC at all.",
  "Standard. Schalte um, wenn du keinen PC hast.": "Default. Switch if you don't have a PC.",
  "Jon nutzt jetzt deinen eigenen Zugang.": "Jon now uses your own access.",
  "Jon nutzt wieder deinen PC oder Pi.": "Jon uses your PC or Pi again.",
  "Du bleibst mit": "You stay connected to",
  "deinem Pi": "your Pi",
  "verbunden. Durchsagen, Bildschirmzeit, Dateien und Jon Chat laufen weiter darüber.": ". Announcements, screen time, files and Jon Chat keep running through it.",
  "Welche KI?": "Which AI?",
  "Offline auf dem Handy": "Offline on the phone",
  "Erst ein Modell laden": "Load a model first",
  "Aktiv": "Active",
  "Jon antwortet offline.": "Jon answers offline.",
  "Modell wählen": "Choose model",
  "Schlüssel hinzufügen": "Add key",
  "Was geht ohne PC?": "What works without a PC?",
  "Chat und Work, Websites bauen und ansehen, Wecker, Timer, Wetter, Websuche, Fitness, Fotos, Dateien und Sprache verstehen, Podcasts – und mit OpenAI, Gemini oder xAI auch Bilder malen. Programme am PC steuern geht nur mit Jon am PC.": "Chat and Work, building and viewing websites, alarms, timers, weather, web search, fitness, understanding photos, files and speech, podcasts – and with OpenAI, Gemini or xAI even painting images. Controlling programs on the PC only works with Jon on the PC.",
  "Deinen Schlüssel bekommst du unter": "You get your key at",
  ". Er bleibt verschlüsselt auf diesem Handy.": ". It stays encrypted on this phone.",
  "Adresse (OpenAI-kompatibel)": "Address (OpenAI compatible)",
  "Schlüssel (optional)": "Key (optional)",
  "API-Schlüssel": "API key",
  "Modell": "Model",
  "Speichern und verwenden": "Save and use",
  "Verbinden": "Connect",
  "Schlüssel entfernen": "Remove key",
  "Fotosynthese als Diagramm": "Photosynthesis as a diagram",
  "Karte des antiken Roms": "Map of ancient Rome",
  "Zeitleiste": "Timeline",
  "Pflanzenzelle": "Plant cell",
  "Gemütliches Zimmer": "Cozy room",
  "Bildeinstellungen": "Image settings",
  "Deine Bilder sind auch in der Bibliothek": "Your images are also in the library",
  "Alles, was Jon für dich erstellt, findest du zusätzlich unter „Bibliothek“.": "Everything Jon creates for you is also in the “Library”.",
  "Hinweis schließen": "Close hint",
  "Ein Bild erstellen": "Create an image",
  "Deine Bilder": "Your images",
  "Jon malt dein Bild …": "Jon is painting your image …",
  "Deine erstellten Bilder erscheinen hier.": "Your created images will appear here.",
  "Ein Bild beschreiben": "Describe an image",
  "Bildoptionen": "Image options",
  "Bilderstellung": "Image creation",
  "Anbieter": "Provider",
  "Standard auf dem Pi": "Default on the Pi",
  "Dein Bild": "Your image",
  "Als Vorlage verwenden": "Use as template",
  "Datei in deiner Bibliothek gespeichert.": "File saved to your library.",
  "Vorgeschlagen": "Suggested",
  "Favoriten": "Favorites",
  "Ordner": "Folders",
  "Dateien": "Files",
  "Neuer Ordner": "New folder",
  "Noch keine Favoriten": "No favorites yet",
  "Deine Bibliothek": "Your library",
  "Dateien aus Work, Uploads und erstellte Bilder werden hier gesammelt.": "Files from Work, uploads and created images are collected here.",
  "Bibliothek durchsuchen": "Search library",
  "Suche": "Search",
  "Datei hinzufügen": "Add file",
  "Einmal hochladen, jederzeit nutzen": "Upload once, use anytime",
  "Frag Jon zu Dateien, die du früher hochgeladen hast – ohne sie erneut hochzuladen.": "Ask Jon about files you uploaded earlier – without uploading them again.",
  "Aktualisieren": "Refresh",
  "Datei hochladen": "Upload file",
  "Erstellen": "Create",
  "Favorit entfernen": "Remove favorite",
  "Zu Favoriten": "Add to favorites",
  "Mit Jon verwenden": "Use with Jon",
  "Kein Ordner": "No folder",
  "Alles für ein Projekt": "Everything for a project",
  "Bündele Chats, Dateien und Anweisungen an einem Ort auf deinem Pi.": "Bundle chats, files and instructions in one place on your Pi.",
  "Projekt erstellen": "Create project",
  "Projektname": "Project name",
  "Anweisungen für Jon": "Instructions for Jon",
  "In Work öffnen": "Open in Work",
  "Projekt analysieren": "Analyze project",
  "Anweisungen speichern": "Save instructions",
  "Täglich": "Daily",
  "Einmalig": "Once",
  "Montags": "Mondays",
  "Dienstags": "Tuesdays",
  "Mittwochs": "Wednesdays",
  "Donnerstags": "Thursdays",
  "Freitags": "Fridays",
  "Samstags": "Saturdays",
  "Sonntags": "Sundays",
  "Morgens": "Mornings",
  "Mittags": "Noon",
  "Nachmittags": "Afternoons",
  "Abends": "Evenings",
  "Wöchentlich": "Weekly",
  "Täglicher Überblick": "Daily overview",
  "KI-Briefing": "AI briefing",
  "Projektfortschritt prüfen": "Check project progress",
  "Aufgaben": "Tasks",
  "Erste Schritte": "Getting started",
  "Eine Aufgabe erstellen": "Create a task",
  "Anzeigen": "Show",
  "Aufgabe planen": "Schedule a task",
  "Was soll Jon erledigen?": "What should Jon do?",
  "Uhrzeit auf dem Pi": "Time on the Pi",
  "Wiederholen": "Repeat",
  "Aufgabe auf dem Pi geplant.": "Task scheduled on the Pi.",
  "Auf dem Pi planen": "Schedule on the Pi",
  "Geplante Aufgabe": "Scheduled task",
  "Aufgabe ausgeführt.": "Task done.",
  "Wird ausgeführt …": "Running …",
  "Jetzt ausführen": "Run now",
  "Aufgabe löschen": "Delete task",
  "Mit Jon arbeiten": "Work with Jon",
  "Code, Dateien und Aufgaben": "Code, files and tasks",
  "Befehle direkt auf dem Pi": "Commands directly on the Pi",
  "Ordner ansehen und bearbeiten": "View and edit folders",
  "Programm starten": "Start program",
  "Webaufgaben an Jon übergeben": "Hand web tasks to Jon",
  "Systemstatus": "System status",
  "Speicher und Verbindung": "Storage and connection",
  "Fernzugriff einrichten": "Set up remote access",
  "Nutze die Möglichkeiten deines Pi auch unterwegs.": "Use what your Pi can do on the go.",
  "Steuere Jon auf deinem Pi, um Software zu entwickeln und anspruchsvollere Aufgaben zu erledigen.": "Control Jon on your Pi to develop software and handle more demanding tasks.",
  "Verbinde zuerst dein Gerät mit deinem Pi.": "Connect your device to your Pi first.",
  "Ich bin mit dem Pi verbunden": "I'm connected to the Pi",
  "Pi-Verbindung verwalten": "Manage Pi connection",
  "Dein Pi": "Your Pi",
  "Verbinde …": "Connecting …",
  "Befehl auf dem Pi": "Command on the Pi",
  "Ausführen": "Run",
  "Programm oder Pfad": "Program or path",
  "Starten": "Start",
  "Gerät": "Device",
  "Freier Speicher": "Free storage",
  "Arbeitsordner": "Work folder",
  "Datei speichern": "Save file",
  "Pi arbeitet …": "Pi is working …",
  "Installiert": "Installed",
  "Beliebt": "Popular",
  "Neu und bemerkenswert": "New and noteworthy",
  "Eigener Skill auf deinem Pi": "Your own skill on your Pi",
  "Skill hinzufügen": "Add skill",
  "Bring Jon eine neue Fähigkeit bei": "Teach Jon a new ability",
  "Neuer Skill": "New skill",
  "Plugins suchen": "Search plugins",
  "Skills suchen": "Search skills",
  "Ansicht": "View",
  "Auf dem Pi noch nicht freigegeben": "Not yet enabled on the Pi",
  "Anweisungen": "Instructions",
  "Skill gespeichert.": "Skill saved.",
  "Chats, Dateien und Projekte suchen": "Search chats, files and projects",
  "Dateien und Projekte": "Files and projects",
  "Nichts gefunden.": "Nothing found.",
  "Suche schließen": "Close search",
  "Wiederhergestellt.": "Restored.",
  "Zurückholen": "Restore",
  "Kein Archiv": "No archive",
  "Archivierte Chats erscheinen hier.": "Archived chats will appear here.",
  "Nachrichten und Anrufe": "Messages and calls",
  "Videos entdecken": "Discover videos",
  "Deine Musik": "Your music",
  "Limit erreicht": "Limit reached",
  "Keine Zeit mehr": "No time left",
  "Diese Apps kannst du aus Jon heraus öffnen. Mit Zurück oder Home kommst du immer wieder zu Jon.": "You can open these apps from Jon. Back or Home always brings you back to Jon.",
  "Deine Anfrage läuft noch. Ich sag dir Bescheid, sobald die Antwort da ist.": "Your request is still pending. I'll let you know as soon as the answer arrives.",
  "Nicht installiert": "Not installed",
  "Anfrage läuft …": "Request pending …",
  "Tippen zum Öffnen": "Tap to open",
  "Apps auswählen": "Choose apps",
  "Für Eltern: freigeben oder entfernen": "For parents: allow or remove",
  "Noch keine App freigegeben": "No app allowed yet",
  "Keine Wiedergabe": "Nothing playing",
  "Spielt gerade": "Now playing",
  "Abspielen": "Play",
  "Weiter": "Next",
  "Für die Steuerung braucht Jon Medienzugriff. Das richtest du unter Einstellungen → Kindersicherung ein.": "To control it, Jon needs media access. Set it up under Settings → Parental controls.",
  "Bildschirmzeit ansehen": "View screen time",
  "Blau": "Blue",
  "Violett": "Violet",
  "Grün": "Green",
  "Mindestens 6 Ziffern.": "At least 6 digits.",
  "Die PINs stimmen nicht überein.": "The PINs don't match.",
  "Recovery-Code stimmt nicht.": "Recovery code is wrong.",
  "Falsche PIN.": "Wrong PIN.",
  "PIN wiederholen": "Repeat PIN",
  "Neue Admin-PIN": "New admin PIN",
  "Recovery-Code": "Recovery code",
  "Admin-PIN": "Admin PIN",
  "Recovery-Code (xxxxxx-xxxxxx-…)": "Recovery code (xxxxxx-xxxxxx-…)",
  "Entsperren": "Unlock",
  "PIN verwenden": "Use PIN",
  "6 bis 12 Ziffern. Diese PIN schützt Kiosk, Kopplung und Geräteeinstellungen.": "6 to 12 digits. This PIN protects the kiosk, pairing and device settings.",
  "Gib deine Admin-PIN ein, um die Verwaltung für 5 Minuten zu öffnen.": "Enter your admin PIN to open management for 5 minutes.",
  "Mit Fingerabdruck": "With fingerprint",
  "PIN vergessen?": "Forgot PIN?",
  "Lokal auf dem Pi": "Local on the Pi",
  "Cloud · schnell": "Cloud · fast",
  "Eigenen API-Schlüssel hinzufügen": "Add your own API key",
  "Modell suchen": "Search models",
  "Anbieter werden vom Pi geladen …": "Loading providers from the Pi …",
  "· Einstellungen → Auf Jon verzichten": "· Settings → Go without Jon",
  "Ohne Internet": "Without internet",
  "Ohne Internet ·": "Without internet ·",
  "Text und Bilder": "Text and images",
  "Jons Standard auf dem Pi": "Jon's default on the Pi",
  "Noch kein Anbieter verbunden. Tippe unten auf „Eigenen API-Schlüssel hinzufügen“.": "No provider connected yet. Tap “Add your own API key” below.",
  "Offline-Modell laden": "Load offline model",
  "Gemma 4 und Co. direkt auf dem Handy": "Gemma 4 and co. directly on the phone",
  "Immer fragen": "Always ask",
  "Nur bei riskanten Aktionen": "Only for risky actions",
  "Nie fragen – alles erlauben": "Never ask – allow everything",
  "Freigaben": "Approvals",
  "Dunkel": "Dark",
  "Hell": "Light",
  "Profil": "Profile",
  "Mein Jon": "My Jon",
  "An · offline auf dem Handy": "On · offline on the phone",
  "eigener Zugang": "own access",
  "Aus · Jon läuft über PC oder Pi": "Off · Jon runs through PC or Pi",
  "Modelle aus der Edge Gallery laden": "Load models from the Edge Gallery",
  "Personalisierung": "Personalization",
  "Erinnerung": "Memory",
  "Konto": "Account",
  "Kein Pi verbunden": "No Pi connected",
  "Schneller antworten": "Answer faster",
  "Nutzung und Grenzwerte": "Usage and limits",
  "Nutzung": "Usage",
  "Kindersicherung": "Parental controls",
  "Kiosk aktiv": "Kiosk active",
  "Kiosk aus": "Kiosk off",
  "Limits, Schlafenszeit, Pause": "Limits, bedtime, break",
  "Standort mitschicken, direkt anrufen": "Send location, call right away",
  "Kindgerechte Antworten, sichere Suche": "Child-friendly answers, safe search",
  "Im Hintergrund verbunden": "Connected in the background",
  "Nachrichten und Durchsagen auch bei geschlossener App": "Messages and announcements even when the app is closed",
  "Benachrichtigungen erlauben, damit du sie siehst": "Allow notifications so you see them",
  "Aus – nur solange Jon offen ist": "Off – only while Jon is open",
  "WLAN, Bluetooth, Ton, Helligkeit": "Wi-Fi, Bluetooth, sound, brightness",
  "Darstellung": "Appearance",
  "Akzentfarbe": "Accent color",
  "Allgemein": "General",
  "Benachrichtigungen sind erlaubt.": "Notifications are allowed.",
  "Benachrichtigungen sind aus.": "Notifications are off.",
  "Sprachmodus": "Voice mode",
  "Sicherheit und Anmeldung": "Security and sign-in",
  "Fernsteuerung": "Remote control",
  "Speicher": "Storage",
  "Datenschutzzentrum": "Privacy center",
  "Datenkontrollen": "Data controls",
  "Fehler melden": "Report a problem",
  "App und Jon auf dem PC oder Pi aktualisieren": "Update the app and Jon on the PC or Pi",
  "Infos": "About",
  "Sicherung": "Backup",
  "Auf den PC oder Pi oder als Datei": "To the PC or Pi or as a file",
  "Was wo gespeichert wird · Alle Daten löschen": "What is stored where · delete all data",
  "Pi-Verbindung trennen": "Disconnect Pi",
  "Jon schließen": "Close Jon",
  "Jon Gerät · FelWorks": "Jon Device · FelWorks",
  "Vorname": "First name",
  "Farbe": "Color",
  "So nennt dich Jon": "What Jon calls you",
  "Was soll Jon über dich wissen und wie soll er antworten?": "What should Jon know about you and how should he answer?",
  "Auf diesem Handy gespeichert": "Stored on this phone",
  "Im Wissen deines Pi gespeichert": "Stored in your Pi's knowledge",
  "Vergessen": "Forget",
  "Jon hat sich noch nichts gemerkt.": "Jon hasn't remembered anything yet.",
  "Neue Erinnerung": "New memory",
  "Merken": "Remember",
  "Ø Antwortzeit": "Ø response time",
  "Zuletzt": "Last",
  "Frei auf dem Pi": "Free on the Pi",
  "Gesamt": "Total",
  "Jons Ordner": "Jon's folder",
  "Bibliothek öffnen": "Open library",
  "Jon hört nur zu, wenn du auf das Mikrofon oder auf „Stimme“ tippst. Was du dann sagst, geht verschlüsselt an deinen Pi.": "Jon only listens when you tap the microphone or “Voice”. What you say then goes to your Pi, encrypted.",
  "Chats, Dateien und API-Schlüssel liegen auf deinem Pi, Schlüssel dort verschlüsselt. Der gewählte KI-Anbieter verarbeitet nur die Anfragen, die du stellst.": "Chats, files and API keys live on your Pi, the keys encrypted. The chosen AI provider only processes the requests you make.",
  "Die Verbindung zum Pi ist Ende-zu-Ende verschlüsselt (AES-GCM) und läuft über dein Heimnetz oder Tailscale.": "The connection to the Pi is end-to-end encrypted (AES-GCM) and runs over your home network or Tailscale.",
  "Was ist passiert?": "What happened?",
  "Bericht auf dem Pi gespeichert.": "Report saved on the Pi.",
  "Bericht auf dem Pi speichern": "Save report on the Pi",
  "Jon Gerät": "Jon Device",
  "Jon auf dem Pi": "Jon on the Pi",
  "Verbindung": "Connection",
  "Anbieter auf dem Pi": "Providers on the Pi",
  "Jon fragt vor Aktionen": "Jon asks before actions",
  "Wenn Jon etwas auf deinem Pi oder PC tut – Dateien ändern, Programme starten, Befehle ausführen –, kann er vorher fragen.": "When Jon does something on your Pi or PC – changing files, starting programs, running commands – he can ask first.",
  "Sicherste Wahl": "Safest choice",
  "Fragt nur bei riskanten Aktionen": "Only asks for risky actions",
  "Jon macht alles ohne Rückfrage – auch Riskantes": "Jon does everything without asking – even risky things",
  "Achtung: Jon kann jetzt auch Dateien löschen oder Befehle ausführen, ohne zu fragen.": "Warning: Jon can now delete files or run commands without asking.",
  "Pi-Verbindung trennen?": "Disconnect the Pi?",
  "Dieses Gerät vergisst den Schlüssel zu deinem Pi. Danach musst du es neu koppeln. Im aktiven Kiosk geht das erst nach dem Verlassen.": "This device forgets the key to your Pi. You'll need to pair it again afterwards. In an active kiosk this only works after leaving it.",
  "Verbindung getrennt.": "Disconnected.",
  "Trennen": "Disconnect",
  "Eigener API-Schlüssel": "Your own API key",
  "Mit einem Cloud-Anbieter antwortet Jon deutlich schneller. Der Schlüssel wird verschlüsselt auf deinem Pi gespeichert – Werkzeuge, Dateien und Aktionen laufen weiter auf dem Pi.": "With a cloud provider Jon answers much faster. The key is stored encrypted on your Pi – tools, files and actions keep running on the Pi.",
  "Nicht erreichbar": "Not reachable",
  "LM Studio richtest du am Pi ein.": "You set up LM Studio on the Pi.",
  "Cloud-Anbieter": "Cloud providers",
  "Über die Pi-Konfiguration": "Via the Pi configuration",
  "Verbunden": "Connected",
  "Welches Modell ein Chat benutzt, wählst du oben im Chat oder unter Einstellungen → Modell.": "You choose which model a chat uses at the top of the chat or under Settings → Model.",
  "Dieser Anbieter ist verbunden. Du kannst den Schlüssel ersetzen oder entfernen.": "This provider is connected. You can replace or remove the key.",
  "Füge deinen API-Schlüssel ein. Er verlässt das Gerät nur verschlüsselt und wird auf dem Pi verschlüsselt abgelegt.": "Paste your API key. It only leaves the device encrypted and is stored encrypted on the Pi.",
  "Standardmodell": "Default model",
  "Standardmodell (optional)": "Default model (optional)",
  "Ollama läuft kostenlos und privat. Standard ist der Pi selbst (localhost). Du kannst auch einen stärkeren Rechner im Heimnetz eintragen.": "Ollama runs free and private. The default is the Pi itself (localhost). You can also enter a stronger computer on your home network.",
  "Ollama benutzen": "Use Ollama",
  "Adresse": "Address",
  "localhost oder 192.168.x.x": "localhost or 192.168.x.x",
  "Teste …": "Testing …",
  "Testen": "Test",
  "Ollama gespeichert.": "Ollama saved.",
  "Akku": "Battery",
  "· lädt": "· charging",
  "Nicht gekoppelt": "Not paired",
  "Verbindungen": "Connections",
  "WLAN": "Wi-Fi",
  "Eingeschaltet": "On",
  "WLAN-Netze": "Wi-Fi networks",
  "Suchen und verbinden": "Search and connect",
  "Ton und Anzeige": "Sound and display",
  "Medienlautstärke": "Media volume",
  "Helligkeit": "Brightness",
  "WLAN, Bluetooth und Helligkeit steuert Jon, sobald der Gerätemodus (Device Owner) eingerichtet ist. Bis dahin nutzt Android seine eigenen Schalter.": "Jon controls Wi-Fi, Bluetooth and brightness once device mode (Device Owner) is set up. Until then Android uses its own switches.",
  "WLAN verbinden": "Connect Wi-Fi",
  "Keine Netze gefunden. Du kannst den Namen auch eintippen.": "No networks found. You can also type the name.",
  "Netzwerkname (SSID)": "Network name (SSID)",
  "Sicherheit": "Security",
  "Offen": "Open",
  "Passwort": "Password",
  "WLAN-Verbindung angefordert.": "Wi-Fi connection requested.",
  "Erlaubt": "Allowed",
  "Noch nicht erlaubt": "Not allowed yet",
  "Live-Text beim Sprechen": "Live text while speaking",
  "Zeigt beim Sprechen live mit, was du sagst": "Shows what you say live while you speak",
  "Durch Sprechen unterbrechen": "Interrupt by speaking",
  "Wie im echten Gespräch: einfach reinreden": "Like a real conversation: just talk over it",
  "Stimme testen": "Test voice",
  "Gespräch starten": "Start conversation",
  "Das Mikrofon in der Eingabezeile wandelt deine Sprache in Text um. Die blaue Taste „Stimme“ startet ein Gespräch mit Jon: Du fragst, Jon antwortet, danach hört er nicht weiter zu. Jon hört nur, wenn du auf eine der beiden Tasten tippst.": "The microphone in the input line turns your speech into text. The blue “Voice” button starts a conversation with Jon: you ask, Jon answers, then he stops listening. Jon only listens when you tap one of the two buttons.",
  "Ich habe nichts gehört. Tippe nochmal auf „Stimme“, wenn du etwas sagen willst.": "I didn't hear anything. Tap “Voice” again if you want to say something.",
  "Ich habe dich nicht verstanden. Tippe nochmal auf „Stimme“.": "I didn't understand you. Tap “Voice” again.",
  "Admin-PIN und Recovery-Code": "Admin PIN and recovery code",
  "Schützt den Ausgang aus dem Kiosk": "Protects the exit from the kiosk",
  "Mit dem Pi verbunden": "Connected to the Pi",
  "Pi koppeln": "Pair Pi",
  "Gerätemodus (Device Owner)": "Device mode (Device Owner)",
  "Eingerichtet": "Set up",
  "Einmalig per USB am PC": "Once via USB on the PC",
  "Für Sprechen und Diktieren": "For talking and dictation",
  "Kiosk ist aktiv. Nur Jon und deine freigegebenen Apps sind erreichbar.": "Kiosk is active. Only Jon and your allowed apps are reachable.",
  "Kiosk verlassen. Jon ist jetzt eine normale App – Zurück oder Home schließt sie, der Samsung-Startbildschirm ist zurück.": "Kiosk left. Jon is now a normal app – Back or Home closes it and the Samsung home screen is back.",
  "Gerätemodus entfernt.": "Device mode removed.",
  "Verwaltung": "Management",
  "Entsperrt · tippen zum Ändern": "Unlocked · tap to change",
  "Noch nicht eingerichtet": "Not set up yet",
  "Verwaltung entsperren": "Unlock management",
  "Verwaltung sperren": "Lock management",
  "Fingerabdruck statt PIN": "Fingerprint instead of PIN",
  "An · neue Fingerabdrücke schalten ihn ab": "On · new fingerprints turn it off",
  "Schneller in die Verwaltung": "Faster into management",
  "Fingerabdruck ist aus.": "Fingerprint is off.",
  "Keine – nur Jon": "None – only Jon",
  "Kiosk · nur Jon und freigegebene Apps": "Kiosk · only Jon and allowed apps",
  "Kiosk kontrolliert verlassen": "Leave kiosk safely",
  "Kiosk aktivieren": "Activate kiosk",
  "Der Gerätemodus wird einmalig per USB vom PC eingerichtet. Dafür dürfen auf dem Handy kurz keine Konten angemeldet sein – danach kannst du sie wieder hinzufügen.": "Device mode is set up once via USB from the PC. No accounts may be signed in on the phone for that moment – you can add them again afterwards.",
  "Medienzugriff für Amazon Music": "Media access for Amazon Music",
  "Für Play, Pause und Titelanzeige": "For play, pause and track display",
  "Erlaubt · Bildschirmzeit misst genau": "Allowed · screen time measures precisely",
  "Für genaue Bildschirmzeit": "For precise screen time",
  "Installiert · nicht aktiv": "Installed · not active",
  "Pi-Verbindung": "Pi connection",
  "Android-Einstellungen": "Android settings",
  "Nur außerhalb des Kiosk": "Only outside the kiosk",
  "Wiederherstellung": "Recovery",
  "Gerätemodus entfernen": "Remove device mode",
  "Dein Recovery-Code": "Your recovery code",
  "Schreib diesen Code auf und bewahre ihn außerhalb des Geräts auf. Mit ihm kommst du in die Verwaltung, falls du die PIN vergisst. Er wird nur jetzt angezeigt.": "Write this code down and keep it away from the device. It gets you into management if you forget the PIN. It's only shown now.",
  "Ich habe den Code sicher notiert": "I've written the code down safely",
  "Jeder Fingerabdruck, der in den Android-Einstellungen dieses Handys gespeichert ist, kann dann die Verwaltung öffnen.": "Every fingerprint saved in this phone's Android settings can then open management.",
  "Nur für Eltern-Finger": "Only for parents' fingers",
  "Schalte das nur ein, wenn auf diesem Handy ausschließlich Fingerabdrücke von Erwachsenen gespeichert sind. Kommt später ein neuer dazu, schaltet Jon den Fingerabdruck automatisch ab.": "Only turn this on if only adults' fingerprints are saved on this phone. If a new one is added later, Jon turns the fingerprint off automatically.",
  "Fingerabdruck ist an.": "Fingerprint is on.",
  "Nicht eingeschaltet.": "Not turned on.",
  "Finger auflegen": "Place finger",
  "Gerätemodus entfernen?": "Remove device mode?",
  "Jon ist dann nicht mehr Geräteverwalter. Der Kiosk lässt sich erst wieder einschalten, wenn der Gerätemodus neu eingerichtet wird.": "Jon is then no longer device administrator. The kiosk can only be turned on again once device mode is set up again.",
  "Entfernen": "Remove",
  "Verbunden.": "Connected.",
  "Verbunden und verschlüsselt.": "Connected and encrypted.",
  "Gekoppelt · gerade nicht erreichbar.": "Paired · not reachable right now.",
  "Öffne in Jon am PC oder Pi „Jon-Gerät einrichten“ und scanne den QR-Code.": "Open “Set up Jon device” in Jon on the PC or Pi and scan the QR code.",
  "QR-Code scannen": "Scan QR code",
  "Oder von Hand": "Or manually",
  "Adresse des Pi": "Address of the Pi",
  "100.x.x.x oder felworks.tailnet.ts.net": "100.x.x.x or felworks.tailnet.ts.net",
  "Kopplungscode": "Pairing code",
  "Starte …": "Starting …",
  "Gesichert.": "Backed up.",
  "Hole die Sicherung …": "Fetching the backup …",
  "Deine Daten sind": "Your data is",
  "Letzte Sicherung:": "Last backup:",
  "Gesichert werden Chats auf dem Handy, Erinnerungen, Fitness, Wecker, Regeln, Profil und Jons Arbeitsordner. Schlüssel und Offline-Modelle bleiben draußen.": "Backed up: chats on the phone, memories, fitness, alarms, rules, profile and Jon's work folder. Keys and offline models stay out.",
  "Auf deinem PC oder Pi": "On your PC or Pi",
  "Jetzt sichern": "Back up now",
  "Verschlüsselt übertragen, die letzten 10 bleiben": "Sent encrypted, the last 10 are kept",
  "Gerade nicht verbunden": "Not connected right now",
  "Täglich automatisch": "Automatically every day",
  "Einmal am Tag, wenn Jon verbunden ist": "Once a day when Jon is connected",
  "Wiederherstellen": "Restore",
  "Als Datei": "As a file",
  "In Downloads speichern": "Save to Downloads",
  "Download/Jon – zum Aufheben oder Umziehen": "Download/Jon – to keep or move",
  "Packe deine Daten …": "Packing your data …",
  "Aus Datei wiederherstellen": "Restore from file",
  "Eine Jon-Sicherung auswählen": "Choose a Jon backup",
  "Sicherung einspielen?": "Restore backup?",
  "Jon übernimmt die Daten aus dieser Sicherung und startet danach neu. Was seitdem auf dem Handy dazugekommen ist, wird ersetzt.": "Jon takes over the data from this backup and restarts afterwards. Anything added on the phone since then will be replaced.",
  "Einspielen": "Restore",
  "Wochentags": "Weekdays",
  "Am Wochenende": "Weekends",
  "Neu": "New",
  "Nächster Wecker:": "Next alarm:",
  "Noch kein Wecker": "No alarm yet",
  "Tippe auf Plus oder sag Jon über „Stimme“: „Weck mich um halb sieben.“": "Tap plus or tell Jon via “Voice”: “Wake me at six thirty.”",
  "Wecker an.": "Alarm on.",
  "Wecker aus.": "Alarm off.",
  "Eigene Dauer in Minuten": "Custom duration in minutes",
  "z. B. 12": "e.g. 12",
  "Timer läuft.": "Timer running.",
  "Timer abbrechen": "Cancel timer",
  "Timer abgebrochen.": "Timer canceled.",
  "Oder sag Jon über „Stimme“: „Timer zehn Minuten.“": "Or tell Jon via “Voice”: “Timer ten minutes.”",
  "Wecker bearbeiten": "Edit alarm",
  "Neuer Wecker": "New alarm",
  "Name (optional)": "Name (optional)",
  "Schule, Training …": "School, training …",
  "Wecker gestellt.": "Alarm set.",
  "Wecker gelöscht.": "Alarm deleted.",
  "Das hat nicht funktioniert.": "That didn't work.",
  "Unbekannter Fehler": "Unknown error",
  "Hier ist etwas schiefgelaufen": "Something went wrong here",
  "Neu laden": "Reload",
  "Wird geladen …": "Loading …",
  "Kein Bild": "No image",
  "Kopiert": "Copied",
  "Jon ist wieder da.": "Jon is back.",
  "Bestätige die Installation, falls Android fragt.": "Confirm the installation if Android asks.",
  "Jon Gerät auf diesem Handy": "Jon Device on this phone",
  "Neu verfügbar": "New version available",
  "Jon ist auf dem neuesten Stand.": "Jon is up to date.",
  "Jetzt aktualisieren": "Update now",
  "Nochmal prüfen": "Check again",
  "Jon auf deinem": "Jon on your",
  "Gerade nicht erreichbar.": "Not reachable right now.",
  "Jon startet neu …": "Jon is restarting …",
  "Läuft …": "Running …",
  "Am PC aktualisiert sich Jon über sein Setup.": "On the PC, Jon updates through its setup.",
  "Jon konnte nicht antworten.": "Jon couldn't answer.",
  "Verbindung unterbrochen.": "Connection interrupted.",
  "Notizen": "Notes",
  "Präsentieren": "Present",
  "Notizen zu Folie": "Notes for slide",
  "Keine Notizen.": "No notes.",
  "Dieses Blatt ist leer.": "This sheet is empty.",
  "Gekürzt – die vollständige Tabelle findest du nach dem Herunterladen.": "Shortened – download to see the full table.",
  "Vorschau": "Preview",
  "Öffnen nicht möglich": "Can't open",
  "Datei wird vom Pi geladen …": "Loading file from the Pi …",
  "Seite": "Page",
  "Kein Text auf dieser Seite.": "No text on this page.",
  "Keine Vorschau": "No preview",
  "Diese Datei kann Jon hier noch nicht anzeigen. Du kannst sie herunterladen.": "Jon can't display this file here yet. You can download it.",
  "Die Vorschau ist gekürzt.": "The preview is shortened.",
  "Mit Jon": "With Jon",
  "Ich höre zu": "I'm listening",
  "Einen Moment …": "One moment …",
  "Jon spricht": "Jon is speaking",
  "Verbinde mit deinem Pi …": "Connecting to your Pi …",
  "Das hat nicht geklappt": "That didn't work",
  "Pi nicht erreichbar": "Pi not reachable",
  "Sprich mit Jon": "Talk to Jon",
  "Tippe auf Jon, um zu unterbrechen": "Tap Jon to interrupt",
  "Mikrofon stumm": "Microphone muted",
  "Tippe auf Jon, wenn du fertig bist": "Tap Jon when you're done",
  "Bitte bestätige die Aktion.": "Please confirm the action.",
  "Mikrofon an": "Microphone on",
  "Sprachmodus beenden": "End voice mode",
  "Hallo, ich bin Jon.": "Hi, I'm Jon.",
  "Dein persönlicher KI-Assistent – zum Reden, Lernen, Arbeiten und Organisieren.": "Your personal AI assistant – for talking, learning, working and organizing.",
  "Los geht's": "Let's go",
  "Wie heißt du?": "What's your name?",
  "So spricht dich Jon an. Du kannst es jederzeit ändern.": "That's how Jon addresses you. You can change it anytime.",
  "Dein Vorname": "Your first name",
  "Wie soll Jon laufen": "How should Jon run",
  "Du kannst das später in den Einstellungen ändern.": "You can change this later in the settings.",
  "Mit Jon am PC oder Pi": "With Jon on the PC or Pi",
  "Voller Funktionsumfang: Dateien, Programme, Fernsteuerung, Jon Chat.": "Full feature set: files, programs, remote control, Jon Chat.",
  "Mit eigenem API-Schlüssel": "With your own API key",
  "Ohne PC: OpenAI, Claude, Gemini und mehr – direkt vom Handy.": "Without a PC: OpenAI, Claude, Gemini and more – straight from the phone.",
  "Gemma 4 und Co. laufen ganz ohne Internet auf deinem Gerät.": "Gemma 4 and co. run on your device without any internet.",
  "Später": "Later",
  "Anhören": "Listen",
  "Ansehen": "View",
  "Öffnen": "Open",
  "Ordner als ZIP": "Folder as ZIP",
  "Auf den Pi": "To the Pi",
  "Pfad auf dem Pi kopiert.": "Path on the Pi copied.",
  "Pfad": "Path",
  "Läuft auf dem Pi …": "Running on the Pi …",
  "Keine Ausgabe.": "No output.",
  "Jon plant …": "Jon is planning …",
  "Erledigt": "Done",
  "Zerlege die Aufgabe in Schritte …": "Breaking the task into steps …",
  "Schritt entfernen": "Remove step",
  "Verwerfen": "Discard",
  "Okay": "Okay",
  "Mehrere Jons, ein Handy": "Several Jons, one phone",
  "Verbinde das Handy zum Beispiel mit dem Pi und deinem PC. Fällt einer aus, springt es zum nächsten.": "Connect the phone to your Pi and your PC, for example. If one fails, it jumps to the next.",
  "Aktiv · verbunden": "Active · connected",
  "Aktiv · gerade nicht erreichbar": "Active · not reachable right now",
  "Erreichbar": "Reachable",
  "Wird geprüft …": "Checking …",
  "Weiteren Jon verbinden": "Connect another Jon",
  "Wechseln": "Switch",
  "Ausfall": "Failover",
  "Automatisch wechseln": "Switch automatically",
  "Wenn der aktive Jon nicht antwortet": "When the active Jon doesn't answer",
  "Jeder Jon hat eigene Chats und Dateien. Durchsagen, Bildschirmzeit und SOS laufen immer über den aktiven Jon.": "Each Jon has its own chats and files. Announcements, screen time and SOS always go through the active Jon.",
  "Das Handy vergisst den Schlüssel zu diesem Jon und wechselt zum nächsten gespeicherten.": "The phone forgets the key to this Jon and switches to the next saved one.",
  "Das Handy vergisst den Schlüssel zu diesem Jon. Zum Wiederverbinden brauchst du einen neuen QR-Code.": "The phone forgets the key to this Jon. To reconnect you need a new QR code.",
  "Prüfen": "Check",
  "Wechseln, hinzufügen oder trennen": "Switch, add or disconnect",
  "Apps verstecken": "Hide apps",
  "An · sichtbar nur nach dem Entsperren": "On · only visible after unlocking",
  "Aus · Apps im Menü sichtbar": "Off · apps visible in the menu",
  "Apps sind versteckt. Nach dem Sperren der Verwaltung sieht sie niemand mehr.": "Apps are hidden. Once management is locked, nobody can see them.",
  "Apps sind wieder sichtbar.": "Apps are visible again.",
  "Kiosk": "Kiosk",
  "Mit Jon verbinden": "Connect to Jon",
  "Noch ein Jon dazu": "Add another Jon",
  "Mit deinem Jon verbinden": "Connect to your Jon",
  "Diesen Jon kennt das Handy nicht.": "The phone doesn't know this Jon.",
  "heute": "today",
  "Zeit aufgebraucht.": "Time used up.",
  "Schlafenszeit.": "Bedtime.",
  "Pause.": "Break.",
  "Gesperrt.": "Locked.",
  "Cloud-Browser": "Cloud browser",
  "in 7 Tagen · Ø": "in 7 days · Ø",
  "frei bis": "free until",
  "von": "of",
  "Deine Daten sind gesichert": "Your data is backed up",
  "Deine Daten sind noch nicht gesichert": "Your data isn't backed up yet",
  "noch nie": "never",
  "gerade eben": "just now",
  "Live ·": "Live ·",
  "Stimme wählen": "Choose voice",
  "Deutsch": "German",
  "Automatisch (Systemsprache)": "Automatic (system language)",
  "Deutsch oder Englisch": "German or English",
  "Dieses Gerät verwendet ausschließlich LAN und Tailscale.": "This device only uses LAN and Tailscale.",
  "Auftrag wurde bereits bearbeitet.": "The job was already handled.",
  "Dieser Auftrag ist nicht erlaubt.": "This job isn't allowed.",
  "Funktion ist auf dem Pi nicht freigegeben.": "This feature isn't enabled on the Pi.",
  "Zuerst Verwaltung entsperren und Kiosk verlassen.": "Unlock management and leave the kiosk first.",
  "Zuerst Verwaltung entsperren.": "Unlock management first.",
  "Bitte eine Minute warten.": "Please wait a minute.",
  "Diese Version aktualisiert sich über Google Play.": "This version updates through Google Play.",
  "Jon ist mit keinem PC oder Pi verbunden.": "Jon isn't connected to a PC or Pi.",
  "Auf deinem PC oder Pi liegt keine App zum Aktualisieren.": "There's no app update on your PC or Pi.",
  "Jon ist schon auf dem neuesten Stand.": "Jon is already up to date.",
  "Erlaube Jon einmal, Apps zu installieren, und tippe dann nochmal auf Aktualisieren.": "Allow Jon to install apps once, then tap update again.",
  "Download abgebrochen.": "Download canceled.",
  "Die geladene App ist beschädigt. Bitte nochmal versuchen.": "The downloaded app is damaged. Please try again.",
  "Diese Funktion braucht den eingerichteten Gerätemodus.": "This feature needs device mode to be set up.",
  "WLAN konnte nicht geändert werden.": "Wi-Fi couldn't be changed.",
  "Bluetooth fehlt.": "Bluetooth is missing.",
  "Bluetooth konnte nicht geändert werden.": "Bluetooth couldn't be changed.",
  "Android begrenzt WLAN-Suchen. Die letzte Liste bleibt verfügbar.": "Android limits Wi-Fi scans. The last list stays available.",
  "SSID ist ungültig.": "SSID is invalid.",
  "Das WLAN-Passwort braucht 8 bis 63 Zeichen.": "The Wi-Fi password needs 8 to 63 characters.",
  "WPA3 wird nicht unterstützt.": "WPA3 isn't supported.",
  "Android hat die WLAN-Konfiguration abgelehnt.": "Android rejected the Wi-Fi configuration.",
  "Zwischen 1 und 240 Minuten.": "Between 1 and 240 minutes.",
  "Fokuszeit geht von 5 bis 240 Minuten.": "Focus time goes from 5 to 240 minutes.",
  "Die Durchsage ist leer.": "The announcement is empty.",
  "Auf diesem Handy ist noch kein Fingerabdruck eingerichtet.": "No fingerprint is set up on this phone yet.",
  "Der Schlüssel ließ sich nicht anlegen.": "The key couldn't be created.",
  "Am Handy wurde ein neuer Fingerabdruck hinzugefügt. Bitte die PIN nehmen und den Fingerabdruck neu einschalten.": "A new fingerprint was added on the phone. Please use the PIN and turn the fingerprint on again.",
  "Foto konnte nicht gespeichert werden.": "The photo couldn't be saved.",
  "Foto nicht gefunden.": "Photo not found.",
  "Foto nicht lesbar.": "Photo not readable.",
  "Diese App ist nicht freigegeben.": "This app isn't allowed.",
  "WhatsApp ist nicht installiert.": "WhatsApp isn't installed.",
  "Unbekannte Musikaktion.": "Unknown music action.",
  "Medienzugriff ist noch nicht freigegeben.": "Media access isn't allowed yet.",
  "Öffne Amazon Music einmal und wähle Musik aus.": "Open Amazon Music once and choose some music.",
  "Amazon Music unterstützt das gerade nicht.": "Amazon Music doesn't support that right now.",
  "Richte zuerst Admin-PIN und Recovery-Code ein.": "Set up the admin PIN and recovery code first.",
  "Admin-PIN erforderlich.": "Admin PIN required.",
  "Verbinde das Gerät zuerst mit deinem Pi.": "Connect the device to your Pi first.",
  "Der Gerätemodus (Device Owner) ist noch nicht eingerichtet.": "Device mode (Device Owner) isn't set up yet.",
  "Der Kiosk braucht Android 9 oder neuer.": "The kiosk needs Android 9 or newer.",
  "Mikrofon zuerst erlauben.": "Allow the microphone first.",
  "Jon ist kein Geräteverwalter.": "Jon isn't device administrator.",
  "Das ist keine Jon-Sicherung.": "That's not a Jon backup.",
  "Die Sicherung enthält ungültige Pfade.": "The backup contains invalid paths.",
  "Speichern fehlgeschlagen.": "Saving failed.",
  "Die Datei lässt sich nicht öffnen.": "The file can't be opened.",
  "Audioformat wird nicht unterstützt.": "Audio format not supported.",
  "Mikrofon ist nicht verfügbar.": "Microphone isn't available.",
  "Das Mikrofon wurde unterbrochen.": "The microphone was interrupted.",
  "Mikrofonberechtigung fehlt.": "Microphone permission missing.",
  "Ungültige Uhrzeit.": "Invalid time.",
  "Mehr als 20 Wecker gehen nicht.": "More than 20 alarms aren't possible.",
  "Ein Timer darf 1 Sekunde bis 24 Stunden laufen.": "A timer can run from 1 second to 24 hours.",
  "Mehr als 10 Timer gehen nicht.": "More than 10 timers aren't possible.",
  "Der Pfad liegt außerhalb des Arbeitsordners.": "The path is outside the work folder.",
  "Die Datei ist zu groß.": "The file is too large.",
  "Die Datei ist zu groß zum Lesen.": "The file is too large to read.",
  "Diesen Ordner gibt es nicht.": "This folder doesn't exist.",
  "Datei nicht verfügbar.": "File not available.",
  "Nicht gefunden.": "Not found.",
  "Zu groß zum Speichern.": "Too large to save.",
  "Das Datum verstehe ich nicht. Nimm heute, gestern oder TT.MM.JJJJ.": "I don't understand the date. Use today, yesterday or DD.MM.YYYY.",
  "Sag mir, was du gemacht hast: Übungen, Dauer oder Strecke.": "Tell me what you did: exercises, duration or distance.",
  "Was soll ich mir merken?": "What should I remember?",
  "Diesen Chat gibt es nicht mehr.": "This chat no longer exists.",
  "Der Chat ist zu lang zum Speichern.": "The chat is too long to save.",
  "Die Nachricht ist leer.": "The message is empty.",
  "Lade zuerst ein Offline-Modell herunter (Einstellungen → Offline-KI).": "Download an offline model first (Settings → Offline AI).",
  "Unbekanntes Modell.": "Unknown model.",
  "Hugging Face hat keine Download-Adresse geliefert.": "Hugging Face didn't provide a download address.",
  "Die Modellliste ist gerade nicht erreichbar.": "The model list isn't reachable right now.",
  "Keine Modellliste gefunden.": "No model list found.",
  "Die neue Liste enthält keine passenden Modelle.": "The new list contains no suitable models.",
  "Dieses Offline-Modell kennt Jon nicht.": "Jon doesn't know this offline model.",
  "Die Datei ist größer als 500 MB.": "The file is larger than 500 MB.",
  "Das Bild lässt sich nicht lesen.": "The image can't be read.",
  "In dieser Datei gibt es keine Tonspur.": "This file has no audio track.",
  "Der Pi ist gerade nicht erreichbar. Wähle „Auf dem Handy behalten“.": "The Pi isn't reachable right now. Choose “Keep on the phone”.",
  "Für den Podcast fehlt das Skript.": "The podcast script is missing.",
  "Die Handy-Stimme ist nicht bereit. Installiere unter Android eine deutsche Sprachausgabe.": "The phone voice isn't ready. Install a text-to-speech voice in Android.",
  "Die Sprachausgabe lieferte ein unbekanntes Format.": "The speech output returned an unknown format.",
  "Diesen Anbieter kennt Jon nicht.": "Jon doesn't know this provider.",
  "Die Adresse muss mit http:// oder https:// beginnen.": "The address must start with http:// or https://.",
  "Wähle zuerst einen Anbieter und hinterlege deinen API-Schlüssel.": "Choose a provider first and add your API key.",
  "Der Schlüssel sieht nicht richtig aus.": "The key doesn't look right.",
  "Unbekannter Anbieter.": "Unknown provider.",
  "Trage zuerst die Adresse deines Servers ein.": "Enter your server's address first.",
  "Wähle unter Einstellungen → Auf Jon verzichten einen KI-Anbieter.": "Choose an AI provider under Settings → Go without Jon.",
  "Für deinen eigenen Server fehlt die Adresse.": "The address for your own server is missing.",
  "Dieses Werkzeug gibt es nicht.": "This tool doesn't exist.",
  "Was soll auf dem Bild sein?": "What should be in the image?",
  "Bilder kann Jon ohne PC nur mit OpenAI, Gemini oder xAI erstellen.": "Without a PC Jon can only create images with OpenAI, Gemini or xAI.",
  "Der Anbieter hat kein Bild geliefert.": "The provider didn't return an image.",
  "Diese Seite ist im Kindermodus gesperrt.": "This page is blocked in kids mode.",
  "Dieses Bild geht im Kindermodus nicht.": "This image isn't possible in kids mode.",
  "Wonach soll ich suchen?": "What should I search for?",
  "Danach sucht Jon im Kindermodus nicht.": "Jon doesn't search for that in kids mode.",
  "Keine Treffer gefunden.": "No results found.",
  "Das ist keine gültige Adresse.": "That's not a valid address.",
  "Nur Webseiten mit http oder https.": "Only web pages with http or https.",
  "Seiten im Heimnetz liest Jon so nicht.": "Jon doesn't read home network pages this way.",
  "Nur die LAN- oder Tailscale-Adresse des Pi eingeben.": "Only enter the Pi's LAN or Tailscale address.",
  "Eine private LAN- oder Tailscale-Adresse verwenden.": "Use a private LAN or Tailscale address.",
  "Im Desktop-Assistenten „Jon-Gerät einrichten“ einen VPN-Code erzeugen.": "Create a VPN code in the desktop assistant “Set up Jon device”.",
  "Pi oder Code nicht erreichbar. Tailscale und den aktuellen Kopplungscode prüfen.": "Pi or code not reachable. Check Tailscale and the current pairing code.",
  "Kopplung beendet": "Pairing ended",
  "Unbekannte Berechtigung.": "Unknown permission.",
  "Bluetooth-Berechtigung fehlt.": "Bluetooth permission missing.",
  "Unbekannte Einstellung.": "Unknown setting.",
  "Ungültiger API-Pfad.": "Invalid API path.",
  "Erlaube das Mikrofon, um mit Jon zu sprechen.": "Allow the microphone to talk to Jon.",
  "Erlaube „Geräte in der Nähe“, damit Jon WLAN-Netze findet.": "Allow “nearby devices” so Jon can find Wi-Fi networks.",
  "Unbekannte Aktion.": "Unknown action.",
  "Die geteilte Datei ist nicht mehr da. Bitte nochmal teilen.": "The shared file is gone. Please share it again.",
  "Im Kiosk bleibt Jon offen. Verlasse zuerst den Kiosk.": "In kiosk mode Jon stays open. Leave the kiosk first.",
  "Jon ist mit keinem Rechner verbunden. Frag bitte direkt nach.": "Jon isn't connected to a computer. Please ask in person.",
  "Diese App kennt Jon nicht.": "Jon doesn't know this app.",
  "Deine letzte Anfrage läuft noch.": "Your last request is still pending.",
  "Erlaube die Kamera, um Fotos zu machen.": "Allow the camera to take photos.",
  "Unbekannte Freigabe.": "Unknown approval.",
  "Der Pi ist gerade nicht erreichbar.": "The Pi isn't reachable right now.",
  "Nur einzelne Dateien können auf den Pi.": "Only single files can go to the Pi.",
  "Jon ist mit keinem Rechner verbunden. Ruf direkt über WhatsApp an.": "Jon isn't connected to a computer. Call directly via WhatsApp.",
  "Es laufen bereits Dateiübertragungen.": "File transfers are already running.",
  "Übertragung abgelaufen.": "Transfer expired.",
  "Datei zu groß.": "File too large.",
  "Verlasse zuerst den Kiosk, um Android-Einstellungen zu öffnen.": "Leave the kiosk first to open Android settings.",
  "Tailscale ist nicht installiert.": "Tailscale isn't installed.",
  "Unbekanntes Ziel.": "Unknown target.",
  "Im aktiven Kiosk kann der Pi nicht gewechselt werden.": "The Pi can't be changed while the kiosk is active.",
  "Erlaube die Kamera, um den QR-Code zu scannen.": "Allow the camera to scan the QR code.",
  "Scan abgebrochen.": "Scan canceled.",
  "Das ist kein Jon-Kopplungscode.": "That's not a Jon pairing code.",
  "Der Code braucht 12 Zeichen.": "The code needs 12 characters.",
  "Datei nicht beschreibbar.": "File not writable.",
  "Antwort gehört nicht zu dieser Anfrage.": "The answer doesn't belong to this request.",
  "Keine Antwort vom Pi.": "No answer from the Pi.",
  "Verbinde Jon zuerst mit deinem Pi.": "Connect Jon to your Pi first."
};

const MUSTER: [RegExp, Ersatz][] = [
  [/^Jon (.+) ist bereit – Einstellungen → Updates\.$/, "Jon $1 is ready – Settings → Updates."],
  [/^(\d+) Apps sind freigegeben\.$/, "$1 apps are allowed."],
  [/^(\d+) Apps freigeben$/, "Allow $1 apps"],
  [/^(.+) in Downloads\/Jon gespeichert\.$/, "$1 saved to Downloads/Jon."],
  [/^Fertig · (\d+) Quellen$/, "Done · $1 sources"],
  [/^(\d+) Dateien geteilt – ich nehme die erste\. Die anderen bitte einzeln teilen\.$/, "$1 files shared – I'll take the first one. Please share the others one at a time."],
  [/^Lese (.+) …$/, "Reading $1 …"],
  [/^Zu (.+) hinzugefügt\.$/, "Added to $1."],
  [/^Mehr Zeit für (.+)$/, "More time for $1"],
  [/^(\d+) Min\. (.+) anfragen$/, "Ask for $1 min of $2"],
  [/^Deine Anfrage für (.+) ist unterwegs\. Ich sag dir Bescheid, sobald die Antwort da ist\.$/, "Your request for $1 is on its way. I'll let you know as soon as the answer arrives."],
  [/^SOS gesendet( – mit deinem Standort)?\. (.+)$/, (_, ort, rest) => `SOS sent${ort ? " – with your location" : ""}. ${uebersetzenRoh(rest) ?? rest}`],
  [/^An · (\d+) Jahre · Hausaufgaben-Hilfe$/, "On · age $1 · homework help"],
  [/^An · für (\d+) Jahre$/, "On · for age $1"],
  [/^An · (.+)$/, (_, rest) => `On · ${uebersetzenRoh(rest) ?? rest}`],
  [/^Ruft (.+) an$/, "Calls $1"],
  [/^Schlafenszeit bis (.+) Uhr\. (.+) ist bis dahin gesperrt\.$/, "Bedtime until $1. $2 is locked until then."],
  [/^Gerade ist Pause bis (.+) Uhr\. (.+) geht danach wieder\.$/, "It's break time until $1. $2 works again afterwards."],
  [/^Deine Zeit für (.+) ist für heute aufgebraucht \((\d+) Minuten\)\.$/, "Your time for $1 is up for today ($2 minutes)."],
  [/^Du hast (\d+) Minuten mehr (.+)\. Viel Spaß!$/, "You got $1 more minutes of $2. Have fun!"],
  [/^Diesmal gibt es keine Extra-Zeit für (.+)\.$/, "No extra time for $1 this time."],
  [/^Gute Nacht(, .+)?! Bis (.+) Uhr sind (.+) gesperrt\. Mit mir kannst du trotzdem reden\.$/, "Good night$1! $3 are locked until $2. You can still talk to me."],
  [/^Gute Nacht(, .+)?! Bis (.+) Uhr ist Ruhe\. Mit mir kannst du trotzdem reden\.$/, "Good night$1! Quiet time until $2. You can still talk to me."],
  [/^„(.+)“ wird auf diesem Handy gelöscht\. Das lässt sich nicht rückgängig machen\.$/, "“$1” will be deleted from this phone. This can't be undone."],
  [/^„(.+)“ wird auf deinem Pi gelöscht\. Das lässt sich nicht rückgängig machen\.$/, "“$1” will be deleted from your Pi. This can't be undone."],
  [/^Schlafenszeit bis (.+) Uhr$/, "Bedtime until $1"],
  [/^Pause bis (.+) Uhr$/, "Break until $1"],
  [/^läuft bis (.+) Uhr$/, "runs until $1"],
  [/^(\d{1,2}:\d{2}) bis (\d{1,2}:\d{2}) Uhr$/, "$1 to $2"],
  [/^von (\d+) Min\.$/, "of $1 min"],
  [/^Fokuszeit läuft (\d+) Minuten\.$/, "Focus time runs for $1 minutes."],
  [/^Pause für (\d+) Minuten\.$/, "Break for $1 minutes."],
  [/^(\d+(?:[.,]\d+)?) Std\.$/, "$1 h"],
  [/^(\d+) Min\.$/, "$1 min"],
  [/^(\d+) Übungen$/, "$1 exercises"],
  [/^(\d+) Mitglieder$/, "$1 members"],
  [/^(\d+) Fotos gespeichert\.$/, "$1 photos saved."],
  [/^(\d+) Min$/, "$1 min"],
  [/^(\d+) Std (\d+)$/, "$1 h $2"],
  [/^(\d+) Orte$/, "$1 places"],
  [/^Braucht (.+) GB RAM$/, "Needs $1 GB RAM"],
  [/^(.+) ist jetzt Standard\.$/, "$1 is now the default."],
  [/^Mit (.+) · ohne Internet$/, "With $1 · offline"],
  [/^Verbunden · (.+)$/, "Connected · $1"],
  [/^· zuletzt (.+)$/, "· last $1"],
  [/^Verbunden mit (.+) – verschlüsselt über LAN oder Tailscale\.$/, "Connected to $1 – encrypted via LAN or Tailscale."],
  [/^(.+) · (.+) · (.+) GB frei$/, "$1 · $2 · $3 GB free"],
  [/^(\d+) Werkzeuge$/, "$1 tools"],
  [/^Noch (\d+ h(?: \d+ min)?|\d+ min)$/, "$1 left"],
  [/^Frei bis (.+)$/, "Free until $1"],
  [/^frei bis (.+)$/, "free until $1"],
  [/^noch (\d+) Min\.$/, "$1 min left"],
  [/^(.+) · Mehr Zeit\?$/, (_, vorn) => `${uebersetzenRoh(vorn) ?? vorn} · More time?`],
  [/^(.+) · Persönlich$/, "$1 · Personal"],
  [/^(.+) · Auf dem Handy$/, "$1 · On the phone"],
  [/^Verbunden mit (.+)$/, "Connected to $1"],
  [/^(\d+) Modelle · (.+)$/, "$1 models · $2"],
  [/^Erreichbar · (\d+) Modelle$/, "Reachable · $1 models"],
  [/^Mit (.+) verbunden\.$/, "Connected to $1."],
  [/^vor (\d+) Min\.$/, "$1 min ago"],
  [/^vor (\d+) Std\.$/, "$1 h ago"],
  [/^Timer läuft: (\d+) Min\.$/, "Timer running: $1 min"],
  [/^Jon ist jetzt auf Version (.+)\.$/, "Jon is now on version $1."],
  [/^(.+) Seite (\d+)$/, "$1 page $2"],
  [/^Liegt jetzt auf dem Pi: (.+)$/, "Now on the Pi: $1"],
  [/^Ausgabe · (.+)$/, "Output · $1"],
  [/^· (\d+) s · Code (.+)$/, "· $1 s · code $2"],
  [/^Datei: (.+)$/, "File: $1"],
  [/^(.+) ist nicht installiert\.$/, "$1 isn't installed."],
  [/^Die Datei (.+) gibt es nicht\.$/, "The file $1 doesn't exist."],
  [/^(.+) ist noch nicht heruntergeladen\.$/, "$1 hasn't been downloaded yet."],
  [/^Für (.+) brauchst du einen kostenlosen Hugging-Face-Schlüssel \(Einstellungen → Offline-KI\)\.$/, "$1 needs a free Hugging Face key (Settings → Offline AI)."],
  [/^Kein Zugriff auf (.+)\. Öffne (.+), akzeptiere die Lizenz und prüfe deinen Schlüssel\.$/, "No access to $1. Open $2, accept the license and check your key."],
  [/^Hugging Face antwortet mit Fehler (\d+)\.$/, "Hugging Face answered with error $1."],
  [/^Für (.+) brauchst du (.+) GB freien Speicher\.$/, "$1 needs $2 GB of free storage."],
  [/^Für (.+) fehlt noch der API-Schlüssel\.$/, "The API key for $1 is still missing."],
  [/^Wähle zuerst ein Modell für (.+)\.$/, "Choose a model for $1 first."],
  [/^Die Seite antwortet mit Fehler (\d+)\.$/, "The page answered with error $1."],
  [/^Den Ort (.+) finde ich nicht\.$/, "I can't find the place $1."],
  [/^Strom abgelehnt \((.+)\)$/, "Stream rejected ($1)"],
  [/^(.+) gelöscht\.$/, "$1 deleted."],
  [/^Nächster Wecker: (.+) Uhr$/, "Next alarm: $1"],
  [/^Zu (.+) wechseln$/, "Switch to $1"],
  [/^(.+) GB belegt$/, "$1 GB used"],
  [/^Sprachmodell wird geladen … (\d+) %$/, "Downloading speech model … $1 %"],
  [/^Lädt beim ersten Sprechen einmal das Sprachmodell \((\d+) MB\)$/, "Downloads the speech model once the first time you speak ($1 MB)"],
  [/^(.+) GB frei machen$/, "Free up $1 GB"],
  [/^Das Sprachmodell für Live-Text wird gerade geladen \((\d+) MB\)\.$/, "The speech model for live text is being downloaded ($1 MB)."],
  [/^(.+) entfernen\?$/, "Remove $1?"],
  [/^(.+) entfernt\.$/, "$1 removed."],
  [/^Jon nutzt jetzt (.+)\.$/, "Jon now uses $1."],
  [/^(.+) ist nicht erreichbar – Jon nutzt jetzt (.+)\.$/, "$1 isn't reachable – Jon now uses $2."],
  [/^(.+) nicht erreichbar\. WLAN oder Tailscale prüfen\.$/, "$1 not reachable. Check Wi-Fi or Tailscale."],
  [/^Verbindung zu (.+) unterbrochen\.$/, "Connection to $1 interrupted."],
  [/^(.+) · (\d+) Verbindungen$/, "$1 · $2 connections"],
  [/^Öffne auf dem anderen PC oder Pi „Jon-Gerät einrichten“ und scanne den QR-Code\. (.+) bleibt gespeichert\.$/, "Open “Set up Jon device” on the other PC or Pi and scan the QR code. $1 stays saved."],
  [/^Fokuszeit läuft (\d+) Minuten\. So lange ist Ruhe\.$/, "Focus time runs for $1 minutes. Quiet until then."],
  [/^(.+) aktualisieren$/, "Update $1"],
  [/^(.+) öffnen$/, "Open $1"],
  [/^(.+) bereit$/, "$1 ready"],
  [/^von (.+)$/, "from $1"],
  [/^(.+) (\d+) Min\.$/, "$1 $2 min"]
];

const TEILE: [RegExp, string][] = [
  [/(\d+) Min\./g, "$1 min"],
  [/(\d{1,2}:\d{2}) Uhr/g, "$1"],
  [/ · ohne Limit/g, " · no limit"],
  [/Keine Limits/g, "No limits"]
];

function uebersetzenRoh(roh: string): string | null {
  const direkt = WOERTER[roh];
  if (direkt !== undefined) return direkt;
  for (const [muster, ersatz] of MUSTER) {
    if (muster.test(roh)) return roh.replace(muster, ersatz as never);
  }
  let teil = roh;
  for (const [muster, ersatz] of TEILE) teil = teil.replace(muster, ersatz);
  return teil === roh ? null : teil;
}

function uebersetzen(text: string): string | null {
  const roh = text.trim();
  if (!roh || roh.length > 600) return null;
  const neu = uebersetzenRoh(roh);
  return neu === null || neu === roh ? null : text.replace(roh, () => neu);
}

const GESCHUETZT = ".md, .user-bubble, .attachment, .jc-blase, .jc-transkript, pre, code, [contenteditable], [translate=\"no\"]";
const OHNE_KINDER = new Set(["INPUT", "TEXTAREA", "SCRIPT", "STYLE", "svg"]);
const ATTRIBUTE = ["placeholder", "aria-label", "title"];
let beobachter: MutationObserver | null = null;
let aktuell = "de";

function geschuetzt(element: Element | null): boolean {
  return !!element?.closest(GESCHUETZT);
}

function bearbeiten(knoten: Node) {
  if (knoten.nodeType === Node.TEXT_NODE) {
    const eltern = knoten.parentElement;
    if (!eltern || OHNE_KINDER.has(eltern.nodeName) || geschuetzt(eltern)) return;
    const neu = uebersetzen(knoten.nodeValue || "");
    if (neu !== null) knoten.nodeValue = neu;
    return;
  }
  if (knoten.nodeType !== Node.ELEMENT_NODE) return;
  const element = knoten as Element;
  if (geschuetzt(element)) return;
  for (const name of ATTRIBUTE) {
    const wert = element.getAttribute(name);
    if (wert) {
      const neu = uebersetzen(wert);
      if (neu !== null) element.setAttribute(name, neu);
    }
  }
  if (OHNE_KINDER.has(element.nodeName)) return;
  element.childNodes.forEach(bearbeiten);
}

export function sprache(): string {
  return aktuell;
}

export function spracheAnwenden(code: string) {
  const englisch = code === "en";
  const vorher = aktuell;
  aktuell = englisch ? "en" : "de";
  document.documentElement.lang = aktuell;
  if (!englisch) {
    beobachter?.disconnect();
    beobachter = null;
    if (vorher === "en") location.reload();
    return;
  }
  if (beobachter) return;
  bearbeiten(document.body);
  beobachter = new MutationObserver(liste => {
    for (const eintrag of liste) {
      if (eintrag.type === "characterData") bearbeiten(eintrag.target);
      else if (eintrag.type === "attributes") bearbeiten(eintrag.target);
      else eintrag.addedNodes.forEach(bearbeiten);
    }
  });
  beobachter.observe(document.body, {subtree: true, childList: true, characterData: true, attributes: true, attributeFilter: ATTRIBUTE});
}
